name: build 👷‍♂️

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"
    tags-ignore:
      - "**"

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - run: DOCKER_BUILDKIT=1 docker build .
